weights = {
    #Điểm trừ
    "Nghỉ học có phép": -1,
    "Đi trễ": -2,
    "Tóc dài hoặc cắt kiểu không phù hợp": -2,
    "Chạy xe trong sân": -2,
    "Mang dép lào": -2,
    "Vi phạm học tập": -3,
    "Mất trật tự": -3,
    "Không đồng phục, không đeo phù hiệu, không đeo huy hiệu đoàn": -3,
    "Nhuộm tóc, son môi, sơn móng": -3,
    "Đeo bông tai đối với học viên nam và đeo bông tai không đồng nhất với nữ": -3,
    "Nói tục": -3,
    "Nghỉ học không phép": -4,
    "Vệ sinh chưa tốt": -5,
    "Cúp tiết, SHDC, SHL": -5,
    "Vi phạm kiểm tra": -5,
    "Ra khỏi lớp, đeo khẩu trang, mặc áo khoác trong giờ học": -5,
    "Không đội nón bảo hiểm hoặc sai quy cách": -5,
    "Sử dụng điện thoại trong giờ học": -5,
    "Cờ bạc, hút thuốc, uống rượu, bia": -20,
    "Đem các dụng cụ cháy nổ, sắt nhọn, đồi trụy, thuốc lá (thuốc lá điện tử) vào khuôn viên Trung tâm": -20,
    "Phá hoại tài sản": -20,
    "Vô lễ, đánh nhau": -20,
    "Vi phạm pháp luật": -20,
    "Không tham gia phong trào": -20,
    #Điểm cộng
    "Điểm 8": +3,
    "Điểm 9": +4,
    "Điểm 10": +5,
    "Tiết học tốt": +50,
    "Điểm cộng": +1,
    "Điểm thưởng": +1
}
